name: Deploy Glue Scripts to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::338149548627:role/steam-analytics-github-actions-role-dev
          aws-region: us-east-1

      - name: Upload Glue scripts to S3
        run: |
          aws s3 sync glue/ s3://steam-analytics-steam-analytics-aman-2026/glue-scripts/ --delete


      - name: Run applications job
        run: aws glue start-job-run --job-name steam-analytics-applications-job-dev
